{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/{{ required "A valid .Values.rbac.apiVersion entry required!" .Values.rbac.apiVersion }}
kind: RoleBinding
metadata:
  name: {{ template "wethex.fullname" . }}
  labels:
    app: {{ template "wethex.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "wethex.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "wethex.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
