apiVersion: v1
{{- with .Values.secret }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
kind: Secret
metadata:
  labels:
    {{- include "wethex.labels" . | nindent 4 }}
  name: {{ include "wethex.fullname" . }}-session-key
type: Opaque